### ISSUE TITLE
Corridor.GetFeaturelinesByCode - unhandled exception in Civil 3D

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#10]
Hi Paolo,

I seam to be getting a Civil 3D error when using the Node **Corridor.GetFeaturelinesByCode** for some civil files, other files ones work just fine. After the error Dynamo gets stuck in a loop and nothing happens. I have attached the full details description of the error.

I've tested this with Revit-Civil 2018, Revit-Civil 2019, Revit-Civil 2020 with the **CiviConnection 3.0.8** and the same error pop's up.

The curious thing is that the node **Corridor.GetFeaturelinesByCodeStation** works! With no errors on the same files that I'm getting the mentioned error.

![image](https://user-images.githubusercontent.com/49474519/64402407-83aaa980-d07d-11e9-8445-e8d75f0f117f.png)
[Civil 3D error.txt](https://github.com/Autodesk/civilconnection/files/3582273/Civil.3D.error.txt)

Small update:
I've installed an old version of **CivilConnection 1.0.19**  with it's **CivilPython.bundle** and it has no issues, the node does not give me an  error.

Even more strange is that I've uninstalled that old version of CivilConn and went back to CivilConn 3.0.8 and now the node works, for the moment at least. This is so confusing. 

Kind Regards!

**Comment by visualphyzx** [comment]
Thanks Lazarica,

I experienced the similar issue but haven't got the chance to document it. 
Not just Corridor.GetFeaturelinesByCode, for me any nodes to extract corridor featureline will freeze the Revit.
I'm trying to re-compile the repo at some stage but haven't find time.

Regard

**Comment by paoloemilioserra** [comment]
@Lazarica-t please check also in your temp folder the CivilConnection_temp.log file to understand what is happening. CivilConnection older versions did not depend on CivilPython as version 3.x does.
I believe the error you get is from CivilPython, I've fixed an issue with corridor feature lines with no style associated in the latest release 1.4 earlier this week.
@visualphyzx please visit the compiled folder and download the latest versions of the package for the release of Revit and Civil 3D you are using.
https://github.com/Autodesk/civilconnection/tree/master/Compiled
Thanks.

**Comment by Lazarica-t** [comment]
@paoloemilioserra Here is the log file just after the error. There doesn't seem to be that much info in it :) it ends abruptly.

[CivilConnection_temp.log](https://github.com/Autodesk/civilconnection/files/3584638/CivilConnection_temp.log)
