### ISSUE TITLE
Suggestion - WriteToLog Node

### ISSUE THREAD

**Issue by EduardLouis** [Autodesk/civilconnection#13]
Hi Paolo,

What about a node to write text in CivilConnection_temp log file? It's more easy for users to see what Dynamo do while they are waiting or if Dynamo clash we can see what was the last thing made.
It's really easy to look at the log file and is very useful.
![image](https://user-images.githubusercontent.com/10221704/66645974-80cb4780-ec2d-11e9-9271-05f90c2654c3.png)
We can implement another log file but is more simple to have all about our scripts in only one log file.

**Comment by paoloemilioserra** [comment]
@EduardLouis to do that you should write an extension to wrap each node in a graph an subscribe to the events when a Dynamo node computation starts and when it finishes. It may be possible now but it won't work for previous versions of Dynamo Core. I think there are already examples of this.
Or maybe you are thinking of a Pass through with a customizable message to write to the Log?

Like this in 4.0.2 https://github.com/Autodesk/civilconnection/blob/master/Src/CivilConnection/2020/Autodesk2020/CivilApplication.cs#L223

![image](https://user-images.githubusercontent.com/14221455/66698336-c8c29b00-ed0f-11e9-89c3-43accc5ece7d.png)

**Comment by EduardLouis** [comment]
Thanks Paolo. 
I have an old version now a little bit changed, but I'll check all your updates these days.
