### ISSUE TITLE
Mass.ByShapesCreaseStations Issue

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#14]
Hi, 

The node **Mass.ByShapesCreaseStations** does not seam to be working properly in the latest version 4.0.3, it's only generating a single good family and the rest are empty families.
In the a previous version 3.0.8 the node was working properly.

See images below.

CivilConnection vs 4.0.3:
![image](https://user-images.githubusercontent.com/49474519/66739680-ea3f9600-ee79-11e9-9eab-a5d4a0d9888d.png)

![image](https://user-images.githubusercontent.com/49474519/66739593-bebcab80-ee79-11e9-97fc-be174290525b.png)

CivilConnection vs 3.0.8:
![image](https://user-images.githubusercontent.com/49474519/66739639-d72cc600-ee79-11e9-811c-235d8e4e6628.png)

Best regards!

**Comment by paoloemilioserra** [comment]
@Lazarica-t Thanks for reporting this! it is now fixed in 4.0.4

**Comment by Lazarica-t** [comment]
Awesome! Thank you! :)
