### ISSUE TITLE
Mass.ByCrossSections distorted form

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#15]
Hi!

Not sure if the **Mass.ByCrossSections** node is working properly, but the resulting form seems to be distorted.
It might be a Revit Issue, but just cheking.
See images below:

![image](https://user-images.githubusercontent.com/49474519/66804269-b3758880-ef2a-11e9-8542-440de6173943.png)
![image](https://user-images.githubusercontent.com/49474519/66804339-e28bfa00-ef2a-11e9-9c34-442357e74fab.png)

Best regards,

**Comment by paoloemilioserra** [comment]
@Lazarica-t can you share the input data you are using? Civil 3D, Shape.XML, temp .Log etc...?

**Comment by Lazarica-t** [comment]
@paoloemilioserra The files can be downloaded form the link below:
https://we.tl/t-fvOezuscRk

I think it has something to do with the cross sections and Revit gets confused and can't create the correct shape, but then comes the question why does the node **Mass.ByLoftCrossSections** work, does it use a different method for creating the form?

Or maybe I'm doing something wrong when generating the cross sections in Dynamo (you can see more details in the graph I've provided).

Playing a bit in the Revit family I've discovered that the lines/curves that come from these cross sections can't be used to generate a proper form:
![image](https://user-images.githubusercontent.com/49474519/66815478-ff332c80-ef40-11e9-8d87-88268d8cc470.png)
![image](https://user-images.githubusercontent.com/49474519/66815490-02c6b380-ef41-11e9-82d8-e7eb3c10c015.png)

The curious thing is that if I convert the lines/curves to reference lines Revit can create the form:
![image](https://user-images.githubusercontent.com/49474519/66815576-2f7acb00-ef41-11e9-9bbf-980012f31408.png)
![image](https://user-images.githubusercontent.com/49474519/66815584-330e5200-ef41-11e9-82d3-8447b8d876e6.png)

Hope this helps.

KR,
