### ISSUE TITLE
IFCExport - if solid files is open as read-only return error

### ISSUE THREAD

**Issue by EduardLouis** [Autodesk/civilconnection#18]
Hi Paolo,

A colleague found that IFC Export is not working if the file is open as read-only. We use a file management system and to be sure that the file remain the same as the file on CDE we open it as read-only. I'm not sure why is needed to be saved after the geometry is back on the initial position, but an try and catch system for error is good there where the file is saved.

![image](https://user-images.githubusercontent.com/10221704/67076938-d6a47000-f196-11e9-81d0-300bbdb097d1.png)

This is the error if I put this in a python node, with my old branch (in the original master is line 1480 or something like that).
![image](https://user-images.githubusercontent.com/10221704/67077029-03588780-f197-11e9-86e1-edec9c6a3a74.png)

**Comment by paoloemilioserra** [comment]
@EduardLouis Thanks, it is trying to save the file with the solids back in the original position as I'm applying a transformation to get the IFC in the Revit local coordinates, I'm not sure you can rollback a transaction through COM, that is why there is need to save the DWG. I suppose it is possible through .NET (via CivilPython), worth investigating.
