### ISSUE TITLE
Featureline.CoordinateSystemByStation return null

### ISSUE THREAD

**Issue by EduardLouis** [Autodesk/civilconnection#2]
Hi,

There is an error on Intersection method from Dynamo. It's a little bit strange for me, when a featureline polycurve is intersected with a plane XZ of a coordinate system from the Baseline return a list of nurbs. If each curve of the polycurve is intersected with the plane XZ from coordinate system everything works fine. Also if I make a surface on that plan and intersect with the polycurve, works fine. 

![Capture](https://user-images.githubusercontent.com/10221704/58026106-6f6a8d00-7b1e-11e9-9d75-d3596ebc68b9.PNG)

I try something like in below code and works fine, but I'm not sure if it's safe for large amount of data or not. Today trying this changed method on large list, Revit close without any message. Not sure if the issues is from here or from another part. 
```
Plane plane = cs.ZXPlane;
                //max distance of surface to intersect the polycurve
                double maxDistForIntersect = 1000;

                Plane plane = cs.ZXPlane;
                Rectangle rec = Rectangle.ByWidthLength(plane, maxDistForIntersect, maxDistForIntersect);
                Surface recS = Surface.ByPatch(rec);
                PolyCurve pc = this._polycurve;

                Point p = null;
                double d = double.MaxValue;
                dynamic rezIntersect = recS.Intersect(pc);
                foreach (var result in rezIntersect)

```
If there is another better solution for this issue, when Featureline.CoordinateSystemByStation return null (Error - Point is null), please let me know.

**Comment by paoloemilioserra** [comment]
@EduardLouis are you able to share the dataset (DYN, RVT and DWG) and the log file?
If you cannot share Revit and Civil 3D data, please use the Project Refinery Data.Remember node on the results of Featureline.Curve and Baseline.CoordinateSystemByStation.

**Comment by EduardLouis** [comment]
I'll try yo install Project Refinery. Today trying get the result in another script I see that the problem is in fact from Geometry Working Range. When is Medium works fine, when is Large give errors.

Medium Range
![image](https://user-images.githubusercontent.com/10221704/58070943-9d45e500-7ba3-11e9-9b34-21c3514cade8.png)

Large Range
![image](https://user-images.githubusercontent.com/10221704/58071006-d1b9a100-7ba3-11e9-82d9-4b4b12474ca0.png)

And I find my answer in your documentation:
![image](https://user-images.githubusercontent.com/10221704/58071104-252bef00-7ba4-11e9-8340-9e97e34ce382.png)

**Comment by paoloemilioserra** [comment]
Thanks @EduardLouis, it will be addressed in future releases of Dynamo Core, the team is aware of it.
