### ISSUE TITLE
Featureline.PointAtStation elevation values 

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#20]
Hi, 

There seams to be a loss in precision for the **Z** values of the featureline points when the input station has a precision greater the 0.1 digits. This loss in precison is only present if the station is close to a PVI point.

As an example, what I've encountered, for a corridor at the station 166.25 I am getting in Civil 3D an elevation of 2.641m for the baseline and the featureline (the mark point for the featureline just having a 3m offset from the baseline, so the elevations should always be the same for both of them).
When I read the elevations at the same station in Dynamo I get a small difference of a few milliliters.

Normally I would just ignore this small loss in precision but in my case it does effect the model I'm trying to create in Revit.

Not sure if anything can be done to improve or fix this, but other users might want to be aware of this of this.

Best regards!
 Bellow are some screens to show the issue, in which I sample the point values at stations 166, 166.2 and 166.25.
![image](https://user-images.githubusercontent.com/49474519/67634655-79f83200-f8c7-11e9-877c-f312816d7db4.png)
![image](https://user-images.githubusercontent.com/49474519/67635040-196af400-f8cb-11e9-9c5e-baab0144980e.png)

**Comment by paoloemilioserra** [comment]
@Lazarica-t can you try again but with one station value at the time? I noticed you have different lacing set for the nodes. I assume you know what you are doing but just in case.
Also the Log file please.

There is no guarantee that the elevation from the Baseline is the same on the one on the Featureline as in principle they can have different grading, so your assumption is wrong.

**Comment by Lazarica-t** [comment]
Sure, no problem.
Log file: [CivilConnection_temp.log](https://github.com/Autodesk/civilconnection/files/3775898/CivilConnection_temp.log)

Well that doesn't sound to reassuring , since I specifically set the link between the Baseline point and the featureline mark point to have 0% slope (in Civil 3D in the Assembly properties). Weird.

The values are the same as above.
![image](https://user-images.githubusercontent.com/49474519/67635550-46baa080-f8d1-11e9-8978-257634d5b29a.png)
![image](https://user-images.githubusercontent.com/49474519/67635555-4de1ae80-f8d1-11e9-9ccb-89decfb7e588.png)
![image](https://user-images.githubusercontent.com/49474519/67635558-52a66280-f8d1-11e9-8be8-4c798263eb45.png)

**Comment by paoloemilioserra** [comment]
@Lazarica-t what I mean is that Featureline can be independent from the Baseline for what concerns Offset AND Elevation, it's a matter of understanding what you are asking not reassuring.

**Comment by paoloemilioserra** [comment]
@Lazarica-t Can you at least pass the log file of the station you are asking and not 148.45?....

**Comment by paoloemilioserra** [comment]
@Lazarica-t I cannot trust what you are doing. Share the Civil 3D model.

**Comment by paoloemilioserra** [comment]
@Lazarica-t extract the polycurve of the Featureline with code "P2", calculate the coordinate system on the baseline at the station you want, extract the ZXPlane, intersect the plane with the polycurve, extract the Z coordinate of the intersection point, if they are still different it means the polycurve in not horizontal in that point.

Double check with the coordinate system form the Alignment.

**Comment by Lazarica-t** [comment]
@paoloemilioserra That is the log for station 166.25

Here is the log after a fresh run for station 166.25
[CivilConnection_temp.log](https://github.com/Autodesk/civilconnection/files/3775956/CivilConnection_temp.log)

![image](https://user-images.githubusercontent.com/49474519/67636194-c9922a00-f8d6-11e9-8343-bafb36e1f2ac.png)

If you are referring to the value found inside the log 148.45 I believe that is a station used for another node in my dynamo script **Corridor.GetFeaturelinesByCodeStation**.
![image](https://user-images.githubusercontent.com/49474519/67636466-766da680-f8d9-11e9-8188-58a6685d3d5e.png)

Here is the script so you can understand better:
[00_Ref Po_TUN_adf_v2.zip](https://github.com/Autodesk/civilconnection/files/3775989/00_Ref.Po_TUN_adf_v2.zip)

**Comment by Lazarica-t** [comment]
> 
> 
> @Lazarica-t extract the polycurve of the Featureline with code "P2", calculate the coordinate system on the baseline at the station you want, extract the ZXPlane, intersect the plane with the polycurve, extract the Z coordinate of the intersection point, if they are still different it means the polycurve in not horizontal in that point.
> 
> Double check with the coordinate system form the Alignment.

I will check now and come back with the results.

**Comment by Lazarica-t** [comment]
@paoloemilioserra No luck, same values after the intersection with the ZXPlane
Coord system from the Alignment has the same values for X,Y coordinates and vectors as the ones from the Baseline

Thanks for you support, much appreciated.

![image](https://user-images.githubusercontent.com/49474519/67636821-1a0c8600-f8dd-11e9-8469-480bb006bda8.png)
