### ISSUE TITLE
Corridor.Shapes - failed. Points are likely coincident

### ISSUE THREAD

**Issue by EduardLouis** [Autodesk/civilconnection#21]
Hi @paoloemilioserra 

An issues about the shapes. Sometime the points from Civil3D are very close, so that the PruneDuplicate function will keep only one point. That iteration need to be skip.

In first image, the shape XML element. In second image the error in Dynamo. Hope this help.

![image](https://user-images.githubusercontent.com/10221704/69316768-341e5780-0c42-11ea-90f7-f3d9f5354534.png)
![image](https://user-images.githubusercontent.com/10221704/69316797-41d3dd00-0c42-11ea-8fe1-57bcea5c0421.png)

**Comment by paoloemilioserra** [comment]
Will be fixed in new release, thanks

**Comment by yekose** [comment]
Is this error has been fixed? Because i am still getting the same error? Actually this error comes from the BaselineRegion.cs line 423

**Comment by ececorlu** [comment]
Unfortunately, I still get this error too.
