### ISSUE TITLE
Baseline.GetFeaturelinesByCode

### ISSUE THREAD

**Issue by danielgijsbers** [Autodesk/civilconnection#22]
I run into an issue where the Baseline.GetFeaturelinesByCode results in an empty list. If I use the node Baseline.GetFeaturelinesByCodeStation with the same inputs and a station value then this node does produce a fature line.
![2019-12-01_08h56_35](https://user-images.githubusercontent.com/36760593/69911313-ca5c3580-1419-11ea-955e-f41615fb79ca.png)

**Comment by paoloemilioserra** [comment]
@danielgijsbers could you share the log and XMLs produced?

**Comment by danielgijsbers** [comment]
[CivilConnection_temp.log](https://github.com/Autodesk/civilconnection/files/3908206/CivilConnection_temp.log)

remove the txt
[Get FeatureLinesByCodeStation.dyn.txt](https://github.com/Autodesk/civilconnection/files/3908207/Get.FeatureLinesByCodeStation.dyn.txt)

sorry didn't mean to close it.

**Comment by paoloemilioserra** [comment]
can you share the XMLs as well? the one containing the actual data for the featurelines? they are in hte same location as the log.

**Comment by danielgijsbers** [comment]
remove the txt
[CorridorFeatureLines_Bridge.xml.txt](https://github.com/Autodesk/civilconnection/files/3908211/CorridorFeatureLines_Bridge.xml.txt)

**Comment by paoloemilioserra** [comment]
@danielgijsbers there is always this error ERROR: Baseline.GetFeaturelinesFromXML Featureline failed Curve join produced more than one WIRE in PolyCurve
It looks like the geometry scaling is not correct. Which Dynamo version are you using?

**Comment by danielgijsbers** [comment]
Revit 2019

Dynamo core 2.0.3.8810
Dynamo Revit 2.0.3.8811

CivilConnection:
![2019-12-01_14h05_27](https://user-images.githubusercontent.com/36760593/69914353-ab729900-1443-11ea-9edd-b5ac13780ac8.png)


AutoCAD Civil 3D
![2019-12-01_14h03_56](https://user-images.githubusercontent.com/36760593/69914328-7a926400-1443-11ea-9b7c-ba9548dbda15.png)

**Comment by paoloemilioserra** [comment]
@danielgijsbers can you please make sure that in your regional settings the decimal separator symbol is a "." rather than a ","? I'll issue a fix that should work around that in the future.

**Comment by danielgijsbers** [comment]
The decimal symbol is indeed a "," (comma)
