### ISSUE TITLE
unable to run civilconnection2019 after installation of Civil3D2020

### ISSUE THREAD

**Issue by jromkes** [Autodesk/civilconnection#23]
I am trying to run a dynamo script from within a family which previously worked without any problems. After some time, in which I installed Civil3D 2020 and got a new company virusscanner, I get the following error:
![Image 077](https://user-images.githubusercontent.com/58976997/70988629-76607a80-20c2-11ea-9094-663309a6ef4d.png)
CivilConnection still runs fine from a Revit project, it's only from a family that I get the error. Is this a known issue and how do I fix it.

Kind regards, Jaco Romkes

**Comment by paoloemilioserra** [comment]
@jromkes thanks for reaching out. CivilConnection is not designed to work in Families. Even so, the error was raised in one of the last updates, please make sure you update have the latest version of CivilConnection installed.

**Comment by EduardLouis** [comment]
The same error for me. If I have Civil3D 2020 installed, CivilConnection didn't work for version 2019. No matter if is in a family or project document.
Reading DrawingSettings from doc gave error. Not only DrawingSettings, but there the script is stop.

**Comment by danielgijsbers** [comment]
@EduardLouis if you like we can schedule a short zoom call on wednesday, Perhaps I can help you out.

**Comment by EduardLouis** [comment]
@danielgijsbers sorry for my late reply.
I solved this changing the versions for Acad Application to 23:
` string m_sAcadProdID = "AutoCAD.Application.23";`

and keep only the Roadway app version for 2019
`            string[] progids = new string[] {
                "AeccXUiRoadway.AeccRoadwayApplication.13.0"} // 2019
`
