### ISSUE TITLE
CivilApplication node changes Revit units

### ISSUE THREAD

**Issue by ntikb** [Autodesk/civilconnection#25]
When using the node "CivilApplication.CivilApplication" in a script, units in Revit change from mm to m. Is this a bug or a feature?:)

CivilConnection2020 4.0.4
Dynamo Core 2.3.0.5885
Dynamo Revit 2.3.0.6270
Revit 2020.2
 
Regards
Klaus Bang
NTI A/S

**Comment by paoloemilioserra** [comment]
@ntikb this is a feature as the units from Civil 3D are either meters or feet.
