### ISSUE TITLE
RevitUtils.CreateFamilyInstance

### ISSUE THREAD

**Issue by danielgijsbers** [Autodesk/civilconnection#27]
Hi,

I keep running into an issue with the RevitUtils.CreateFamilyInstance node. IF you provide it with a range of station values it places the first and then it produces nulls. I have done this before and then It worked.

![2020-01-20_07h05_44](https://user-images.githubusercontent.com/36760593/72702663-cc0dc400-3b53-11ea-8ae6-47200465e036.png)

**Comment by danielgijsbers** [comment]
@paoloemilioserra the file: 03.1_Place Families_2.0_DP.dyn was used for this.

**Comment by paoloemilioserra** [comment]
@danielgijsbers what does the log file say?
