### ISSUE TITLE
CivilPython doesnt work

### ISSUE THREAD

**Issue by jnky1812** [Autodesk/civilconnection#28]
I cant get Civil Connection 2020 to work I think due to CivilPython not working.
After setting CivilPython.dll to unblocked when I try to run the Command PYTHON inside Civil3d I get an unhandled exception.

Could not load file or assembly 'Microsoft scripting. Version=1.1.0.20,Culture=neutral, PublicKeyToken=7f709c5b713576e1' or one of its dependancies. The system cannot find the file specified.

In Dynamo I get the same error as though I have a mismatch between applications and the Civil Connection version which I do not

edit .. (Autodesk support sent me here)

**Comment by paoloemilioserra** [comment]
Have you got an earlier version of Revit installed on the machine? Try to install IronPython 2.7 from the website or in alternative Dynamo Core as an independent install. Also Dynamo for Civil 3D will install the necessary files on your machine.

**Comment by jnky1812** [comment]
installing Dynamo for Civil3d fixed the CivilPython problem but I still get the Civil Application node operation failed error, I only have Revit 2020 and Civil3d 2020 but would have had previous versions since uninstalled.

**Comment by jnky1812** [comment]
This is the specific message

Warning: CivilApplication..ctor operation failed. 
Value cannot be null.
Parameter name: path1

I definately do not have old versions installed but may have done on this machine in the past, what does the node look for to determin the installed version? is it a registry key or a file\folder in AppData?

**Comment by paoloemilioserra** [comment]
It's looking for a running Civil 3D Application (not MAP 3D, not AutoCAD) https://github.com/Autodesk/civilconnection/blob/master/Src/CivilConnection/2020/Autodesk2020/CivilApplication.cs#L66


Which version of CivilConnection are you running? Can you try downgrade to 3.0.8?

I will closed the issue as it is on CivilPython.

**Comment by dschenau85** [comment]
I Run civil3D 2022. But I have installed AutoCAD and MAP3D.
![image](https://user-images.githubusercontent.com/53792273/188600172-61b6d5c4-5881-433c-8eb8-ddb1be70f25e.png)
