### ISSUE TITLE
Read featurelines from a corridor with regions from DataShortcut

### ISSUE THREAD

**Issue by EduardLouis** [Autodesk/civilconnection#3]
Hi @paoloemilioserra,

I glad to work again with CivilConnection, but there are few things that are challenging me. Not sure if in your previous versions  works to read featurelines from corridors as reference from data shortcut but I think yes, if I remember correctly. The problem is when a reference corridor from data shortcut have regions. These regions return nulls in the code and the featureline cannot be created because the stating and end station cannot be computed. 

I took the Roadway corridor from your dataset, split that one in 3 regions and I create a reference in a new drawings.
![image](https://user-images.githubusercontent.com/10221704/58234538-76c0af00-7d47-11e9-9d1e-5d92e5994ac0.png)
When I read the featureline from the source drawing everything is fine but reading featureline from reference corridor from data shortcut give nulls.
![image](https://user-images.githubusercontent.com/10221704/58234669-bc7d7780-7d47-11e9-9923-dbcaad8a11c2.png)

I create a new branch  and changed the code a little bit, but I cannot push my fork with the changes. So here my changes:
for baseline.cs
 ```
      public double[] GetArrayStationOffsetElevationByPoint(Point point)
        {
            Utils.Log(string.Format("Baseline.GetArrayStationOffsetElevationByPoint started...", ""));

            AeccAlignment alignment = this.Alignment.InternalElement as AeccAlignment;

            double station = 0;
            double offset = 0;
            double elevation;

            alignment.StationOffset(point.X, point.Y, out station, out offset);

            try
            {
                double profileStart = this._baseline.Profile.StartingStation;
                double profileEnd = this._baseline.Profile.EndingStation;
                if (profileStart > station && Math.Abs(profileStart-station) < 0.001)
                {
                    station = profileStart;
                }
                else if (profileEnd < station && Math.Abs(profileEnd - station) < 0.001)
                {
                    station = profileEnd;
                }
                    elevation = point.Z - this._baseline.Profile.ElevationAt(station);
            }
            catch
            {
                elevation = point.Z - PointByStationOffsetElevation(station, offset, 0).Z;
            }

            Utils.Log(string.Format("Baseline.GetArrayStationOffsetElevationByPoint completed.", ""));

            return new double[] { station, offset, elevation };
        }
```
for featureline.cs:
```
        internal Featureline(Baseline baseline, PolyCurve polycurve, string code, SideType side, int regionIndex = 0)
        {
            this._baseline = baseline;
            this._polycurve = polycurve;
            this._code = code;
            this._side = side;
            this._regionIndex = regionIndex;
            try
            {
                var region = this.Baseline.GetBaselineRegions()[this._regionIndex];
                this._start = region.Start;
                this._end = region.End;
            }
            catch
            {
                this._start = Convert.ToDouble(baseline.GetStationOffsetElevationByPoint(polycurve.StartPoint)["Station"]);
                this._end = Convert.ToDouble(baseline.GetStationOffsetElevationByPoint(polycurve.EndPoint)["Station"]);
            }

        }
```
for profile.cs: - also to ignore the error when there is a very small difference between starting station of the profile and starting station of the baseline.

```
        public double GetElevationAtStation(double station)
        {
            //ignore if error is less than 1mm
            if (this.StartStation > station && Math.Abs(this.StartStation - station) < 0.001)
            {
                station = this.StartStation;
            }
            else if (this.EndStation < station && Math.Abs(this.EndStation - station) < 0.001)
            {
                station = this.EndStation;
            }

            return this._profile.ElevationAt(station);
        }
```

Can you try these changes in the corridor (to have regions on a reference corridor from data shortcut) and read the featurelines? There is another better approach for that? My code still give errors if the featureline have the same code: at intersection with another corridor where is a new road line give errors - the featureline jump from one line to another =>in few particular cases, the station computed with my code differ from the baseline region start / end station.

![tretr](https://user-images.githubusercontent.com/10221704/58237910-e1291d80-7d4e-11e9-8056-3d5e5635231d.png)

**Comment by paoloemilioserra** [comment]
Eduard can you try the latest version? Also rememebr to update CivilPython. Also we found that it is best to have a baseline for each assemblyespecially if the regions are consecutive and share a station in common. You can gabe multiple regions on the same baseline if the regions are not sharing a station.

**Comment by paoloemilioserra** [comment]
@EduardLouis I've tested the latest version and I was able to retrieve the featurelines from a DataShortcut corridor with multiple regions with no issues.

**Comment by EduardLouis** [comment]
@paoloemilioserra thanks!
Works perfect now! 
The only thing is structure of the Featureline lists but this is not CivilConnection, is Civil3D. In a referenced corridor featurelines are connected different from one region to another, if the featureline have the same Code Point Name.
