### ISSUE TITLE
Civil Connections - for Civil 3D using Dynamo sandbox. - (without Revit installation machines))

### ISSUE THREAD

**Issue by r327079** [Autodesk/civilconnection#34]
Hi Paolo,

Can you suggest or modify Civilconnection codes by removing Revit dependencies. In other words enabling direct use of Dynamo with Civil 3D - (2018 ver.). Revit usage is limited for Highway Designers using Civil 3D. 
Andrew Milford had published some ppt for "Civil 3D Data Mining with Dynamo". (ref. - CES226095 on Autodesk university). 

Thanks

Robin

**Comment by paoloemilioserra** [comment]
Hi Robin,

thanks for reaching out. The purpose of CivilConnection has always been, is, and will remain to exchange information between Revit and Civil 3D, so I cannot accept your request.

You are free to leverage the parts of CivilConnection you find useful in your own projects, just don't forget to mention the copyrights notes if you wish to do so.

Thanks

**Comment by r327079** [comment]
Hi Paolo ,
Thanks for reply. I would request you to please help in this regard. I had shared the codes in AU2018.Civil3D with you on Github. (r327079)I am using  Visual Studio 2019 for coding and it is showing error. I am relatively new to dot net coding and Github.

I would highly appreciate if you can review and assist me in completing this coding done. I have Millford's paper on codes required for Dynamo - Civil 3D connections.  Attached for reference. 
Thanks & Best RegardsR Upadhyay 

    On Friday, 27 March, 2020, 07:28:36 pm IST, paoloemilioserra <notifications@github.com> wrote:  
 
 


Hi Robin,

thanks for reaching out. The purpose of CivilConnection has always been, is, and will remain to exchange information between Revit and Civil 3D, so I cannot accept your request.

You are free to leverage the parts of CivilConnection you find useful in your own projects, just don't forget to mention the copyrights notes if you wish to do so.

Thanks
