### ISSUE TITLE
AppliedSubassemblyShape issue.

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#37]
Hi,

There seams to be am issue with the **AppliedSubassemblyShape's** that I get from the nodes **BaselineRegion.Shapes** and **Corridor.Shapes** when dealing with certain types of Corridors.
The problem I'm facing is when I have a corridor made up multiple Regions with different Assemblies, see example below:
![image](https://user-images.githubusercontent.com/49474519/80865609-47266080-8c93-11ea-843a-02199b5dd41c.png)
Red = 1st Sub-Region with it's respective Assembly
Blue = 2nd Sub-Region with it's respective Assembly

As you can see the two Sub-Regions form a continuous Region with station 104.78 being common.

I've noticed some time ago that I get some gaps in the Mass's obtained using **Mass.ByShapes** nodes, but did not quite understand why this was happening
![image](https://user-images.githubusercontent.com/49474519/80865889-b51f5780-8c94-11ea-96ba-b02041bc9ee0.png)
So the conclusion that I arrived at is that is has something to do with the Subassembly Shape not being properly detected at the intersection of the 2 Sub-Regions.

For some reason the Assembly at station 104.78 where the two Sub-Region's intersect is taken from the previous Sub-Region 1 when in reality it should be from the second one.
![image](https://user-images.githubusercontent.com/49474519/80866125-c5840200-8c95-11ea-9b37-1df371f7a768.png)

I'm assuming the ***.Shapes** nodes are trying to avoid 2 Assembly instances existing at the same location.. is this correct? Or is there another explanation..
Is there any solution when faced with Corridors that have multiple Regions with different Assemblies?

Thank you!

**Comment by paoloemilioserra** [comment]
@Lazarica-t The problem is not in the node but in the way your Corridor is built.
If you need two different assemblies in two consecutive regions you should consider two separate baselines, one per assembly.
The applied subassemblies in the first station of the region that follows are the same as in the region that precedes. This is a Civil 3D behavior that is used to compute the Corridor Feature lines and it cannot be changed.

**Comment by Lazarica-t** [comment]
Ok, I will take this into account when building the Mass Shapes.
Thanks.
