### ISSUE TITLE
not creating xml file in TEMP folder

### ISSUE THREAD

**Issue by atultegar** [Autodesk/civilconnection#4]
Hi,
I am using Civil Connection 2018 with Civil 3D 2018 and Revit 2018. 
Whenever I use the node Corridor.GetCodes or Corridor.GetFeaturelines, Dynamo is not responding.
May be it is because of, in the new version of Civil Connection, corridor featurelines are exported to XML file in TEMP folder and in my case it is not creating any XML file, it stucks there.
But whenever I used the previous version of Civil Connection (2.0.4) it works perfectly, because it is not exporting any data to XML, it directly reads from Civil 3D.

Thanks
Atul Tegar

**Comment by paoloemilioserra** [comment]
Atul, you need to update the CivilPython as well to use it with the latest version of CivilConnection

**Comment by danielgijsbers** [comment]
The odd thing is that we installed / updated all the machines

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by paoloemilioserra** [comment]
Just to clarify, the improvement in speed with version 3 is possible because of the silent export, so I'm not going to reverse it back. Can you confirm you launched CivilPython and confirmed to Always Load please?

**Comment by atultegar** [comment]
Hi Paolo,
I have updated the CivilPython to latest version, now its working fine. Thanks

**Comment by paoloemilioserra** [comment]
Thanks for taking the time Atul!
