### ISSUE TITLE
Alignment.GetCurves issue

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#40]
Hi, 

The node **Alignment.GetCurves** does not seem to be working properly in update 5.0.0
For some Alignments I receive this error:
![image](https://user-images.githubusercontent.com/49474519/88156177-bae06580-cc11-11ea-8288-ba71ec1ac383.png)

Previous version 4.0.4 no issues:
![image](https://user-images.githubusercontent.com/49474519/88156230-d0ee2600-cc11-11ea-8b2c-241e32556a84.png)

Code fault seems to be here:
![image](https://user-images.githubusercontent.com/49474519/88156374-0266f180-cc12-11ea-8f40-1cd536181efa.png)

KR,

**Comment by paoloemilioserra** [comment]
will fix in next release
