### ISSUE TITLE
Install not functioning as expected 

### ISSUE THREAD

**Issue by vvv29** [Autodesk/civilconnection#41]
Hello, 

Im trying to install on C3D 2019, Revit 2019 and Dynamo 2.0.3.8811

First ,I copied the Zip file found in "Dynamo_CivilConnection\civilconnection-master\Compiled\2019"  to the dynamo Revit packages and extracted in the folder. 

Secondly, i edit the xml file to later find out i did not have to do this step, then i installed the CivilPython.dll to the following route "C:\ProgramData\Autodesk\ApplicationPlugins\CivilPython.bundle" i am able to execute the python, -python command in the cmd, and made it always loadable in C3D

Then i set civil 3d in imperial system, and civil 3D workspace, i opened revit imperial as well, i imported and acquired the coordinates from the DWG file.

I expected to see the the package in the dynamo library UI but it wont show the package or its nodes. 

![image](https://user-images.githubusercontent.com/67920017/89944506-5607a200-dbf6-11ea-9e5b-d31ce003c283.png)

Any help or suggestion would be appreciated, thank you!

**Comment by paoloemilioserra** [comment]
@vvv29 Did you unblock the dll files in the Dynamo package?

**Comment by vvv29** [comment]
Yes i unblocked the packages, it doesnt show the unblock box ot be unchecked

![image](https://user-images.githubusercontent.com/67920017/89949153-d1b91d00-dbfd-11ea-8894-aebce3eea9a3.png)

**Comment by paoloemilioserra** [comment]
@vvv29 Did you relaunch Revit?

**Comment by paoloemilioserra** [comment]
@vvv29 Can you show me the folder that contains the packages?

**Comment by paoloemilioserra** [comment]
@vvv29 can you show me the console in Dynamo?

**Comment by paoloemilioserra** [comment]
@vvv29 also Fractal Tree is not showing up, what is this package?

**Comment by vvv29** [comment]
Yes, i have restarted the computer after all installs. 

![image](https://user-images.githubusercontent.com/67920017/89949996-1e512800-dbff-11ea-86ad-293c7f664f58.png)


"
Dynamo log started 2020-08-11 21:17:19Z

Requesting version update info...
Dynamo -- Build 2.0.3.8810
Duplicate migration type registered for SunPathDirection
The folder 'C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\CivilConnection2019\definitions' does not exist
Dynamo will use the package manager server at : https://www.dynamopackages.com
Exception encountered scanning the package directory at C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\dyf
System.Exception:
C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\dyf\pkg.json contains a package without a header.  Ignoring it.
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory)
Exception encountered scanning the package directory at C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\extra
System.Exception:
C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\extra\pkg.json contains a package without a header.  Ignoring it.
   at Dynamo.PackageManager.PackageLoader.ScanPackageDirectory(String directory)
The folder 'C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\CivilConnection2019\packages' does not exist
System.InvalidOperationException:
There already exists an AlsoKnownAs mapping for Fill Pattern Targets.

System.InvalidOperationException:
There already exists an AlsoKnownAs mapping for Unit Types.

DynamoPackageManager (id: FCABC211-D56B-4109-AF18-F434DFE48139) extension is added
Backup files timer is started with an interval of 60000 milliseconds
SYSTEM:Environment Path:C:\Program Files\Autodesk\Revit 2019\AddIns\SteelConnections;C:\Program Files\Autodesk\Revit 2019\en-US;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Common Files\Autodesk Shared\;C:\WINDOWS\System32\OpenSSH\;C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;;C:\Users\admin\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Autodesk\Revit 2019;C:\Program Files\Dynamo\Dynamo Core\2\
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384,16384
RENDER : Rendering Tier: 2
RENDER : Pixel Shader 3 Supported: True
RENDER : Pixel Shader 4 Supported: False
RENDER : Software Effect Rendering Supported: True
RENDER : Maximum hardware texture size: 16384,16384
DynamoManipulationExtension (id: 58B0496A-E3F8-43D9-86D2-94823D1D0F98) view extension is added
LibraryUI (id: 85941358-5525-4FF4-8D61-6CA831F122AB) view extension is added
NotificationsExtension (id: ef6cd025-514f-44cd-b6b1-69d9f5cce004) view extension is added
Rhythm View Extension (id: 5435824A-A3A1-4FC1-AF42-E5139041740F) view extension is added
PackageManagerViewExtension (id: 100f5ec3-fde7-4205-80a7-c968b3a5a27b) view extension is added
Welcome to Dynamo!
00:00:00.9684813 elapsed for loading Dynamo main window.
WPF Render Mode: SoftwareOnly
Update available: 2.0.4.0
Update download started...
Update download progress: 0%
ERR_ABORTED
Update download progress: 10%
Update download progress: 20%
Update download progress: 30%
Update download progress: 40%
Clearing workspace...
Update download progress: 50%
Update download progress: 60%
Update download progress: 70%
Update download progress: 80%
Update download progress: 90%
Saving C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN ...
Backup file is saved: C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\backup\backup.DYN
Update download progress: 100%
Update download complete.
Update download complete.
Clearing workspace...
Clearing workspace...

"

Fractal Tree is a package i was testing but i can delete no problem

**Comment by paoloemilioserra** [comment]
@vvv29  The folder 'C:\Users\admin\AppData\Roaming\Dynamo\Dynamo Revit\2.0\packages\CivilConnection2019\packages' does not exist, you have something wrong here.
I suggest you download the package again and match the installation path like the other packages.

**Comment by vvv29** [comment]
Yes i have tried this, i will try again, making a clean install, oddly it is showing in the package manager as shown in the first image, but wont load properly in the UI, i deleted the packages i wasnt using. All other packages function properly and are installed on the same path as the CivilConnection

**Comment by paoloemilioserra** [comment]
the package manager only reads the pkg.json file it doesn't look at the actual folder structure.

**Comment by paoloemilioserra** [comment]
@vvv29 can you show me the CivilConnection2019 folder content?

**Comment by vvv29** [comment]
yes! Dyf and Extra folders are empty Bin has the xml and DLL 

![image](https://user-images.githubusercontent.com/67920017/89951152-45a8f480-dc01-11ea-8dca-69aab66ce9e5.png)

**Comment by paoloemilioserra** [comment]
@vvv29  let's edit the pkg.json, it might be possible that it is pointing to the wrong assembly name/version

`{"license":"Apache License, Version 2.0",
"file_hash":null,
"name":"CivilConnection2019",
"version":"5.0.0",
"description":"Connect Civil 3D and Revit",
"group":"",
"keywords":null,
"dependencies":[],
"contents":"",
"engine_version":"2.0.2.6826",
"engine":"dynamo",
"engine_metadata":"",
"site_url":"https://github.com/Autodesk/civilconnection",
"repository_url":"https://github.com/Autodesk/civilconnection",
"contains_binaries":true,
"node_libraries":["Autodesk2019, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null"]}`


make sure that the last parameter in node_libraries points to the same assembly .DLL you have in the bin folder

**Comment by vvv29** [comment]
okay, that seems to have worked. Now i am seeing the package in the library. 

![image](https://user-images.githubusercontent.com/67920017/89955916-6f1a4e00-dc0a-11ea-8043-42ad18f5f3a1.png)

Thank you now i can continue configuring the CivilConnection.
