### ISSUE TITLE
Mass.ByShapesCreaseStations node and Corridor Bowties Issue

### ISSUE THREAD

**Issue by andmailg** [Autodesk/civilconnection#45]
Hello!
Is there a way to solve the issue caused Mass.ByShapesCreaseStations node that ignores Civil 3D corridor bowties (shapes are not perpendicular to alignment)?
Civil Connection 5.0.1
![mbcs](https://user-images.githubusercontent.com/55160785/98137619-40430980-1ed3-11eb-8900-d105316aa95a.png)
![mbcs_revit](https://user-images.githubusercontent.com/55160785/98137657-49cc7180-1ed3-11eb-9692-97f2ca1765f5.png)
![corr](https://user-images.githubusercontent.com/55160785/98137668-4cc76200-1ed3-11eb-9ec2-b38d58253ce4.png)

**Comment by paoloemilioserra** [comment]
you need to provide the appropriate list of station values: start, bow-tie, end

**Comment by andmailg** [comment]
> you need to provide the appropriate list of station values: start, bow-tie, end

I did so
![dy](https://user-images.githubusercontent.com/55160785/98150364-961dae80-1edf-11eb-97a9-fd6b59fa0e9c.png)

**Comment by paoloemilioserra** [comment]
share the dwg

**Comment by andmailg** [comment]
[issue.zip](https://github.com/Autodesk/civilconnection/files/5489713/issue.zip)

**Comment by paoloemilioserra** [comment]
You need to use a  different method for example Mass by Solid.
![image](https://user-images.githubusercontent.com/14221455/98439637-72cb4d00-20f3-11eb-9045-49625ee4ea60.png)

The coordinates of the applied subassemblies on the bowtie are returned orthogonal to the alignment, nothing I can do about it.

![image](https://user-images.githubusercontent.com/14221455/98439660-9b534700-20f3-11eb-8251-1ebfd146da1e.png)

**Comment by andmailg** [comment]
Ok, thank you very much!
