### ISSUE TITLE
CivilConnection 2021 Signed Certificate

### ISSUE THREAD

**Issue by mike-smith-psomas** [Autodesk/civilconnection#46]
The civil connection 2021 package fails to load with the following error: "A package called CivilConnection2021 found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\CivilConnection2021 could not be verified to have signed dll files.  A dll file found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\CivilConnection2021\bin\Autodesk2021.dll did not have a signed certificate.  Ignoring it."

I have unblocked the .dll .xml and .json files in the package.

**Comment by jfmarquitectura** [comment]
Hello, I have the same Problem. I can't execute Civil connection for revit. I have the same error: 

A dll file found at C:\ProgramData\Autodesk\RVT 2021\Dynamo\2.6\packages\CivilConnection2021\bin\Autodesk2021.dll did not have a signed certificate.  Se omitirá."

Please I need help to get a solution.

I have Revit 2021 and C3D2021 installed.

Thanks in advance.

**Comment by paoloemilioserra** [comment]
Cannot reproduce, uninstall all other packages first, including earlier versions of CivilConnection and try again.
