### ISSUE TITLE
Civil Connection for Revit 2022

### ISSUE THREAD

**Issue by jmcouffin** [Autodesk/civilconnection#47]
Hi there, 
Revit 2022.1 being in the pipeline, I don't know how much effort it represents to port it to revit 2022?
nice tool

**Comment by paoloemilioserra** [comment]
Thanks, it's a lot of effort actually, the Revit API for parameters has changed and without IronPython also CivilPython needs to be rewritten to support CPython3. Currently I do not have the bandwidth to do it, that is why the code has been made public.

**Comment by jmcouffin** [comment]
Thanks for the clarification.

Le ven. 9 juil. 2021 20:35, paoloemilioserra ***@***.***> a
écrit :
