### ISSUE TITLE
Package not showing up

### ISSUE THREAD

**Issue by grittmw** [Autodesk/civilconnection#5]
I installed version 3.0, but it's not showing up in Dynamo. I have Dynamo from Civil3D 2.1.1. Do I need to have Revit 2020 installed?

**Comment by danielgijsbers** [comment]
Hi 
Did you unblock the dll?

**Comment by danielgijsbers** [comment]
I am not sure if the CC is working under the Dynamo for AutoCAD, I have tested that.

**Comment by grittmw** [comment]
The dll isn't blocked. Other packages are loaded correctly.
I tried the package in Dynamo for Revit, there it's loading fine. So it's not working in Dynamo under Civil3D/AutoCAD.

**Comment by paoloemilioserra** [comment]
Yes CivilConnection is a Dynamo for Revit package.
