### ISSUE TITLE
Problem with Installation of packages 

### ISSUE THREAD

**Issue by Mairh93** [Autodesk/civilconnection#58]
Hello, 

I followed the instruction of the video (https://www.youtube.com/watch?v=MAWkHWZMf7U), but it seems that in Dynamo (2.6) the nodes dont work., also in civil 3D when I write python nothing happens. I use Revit 2021  and Civil3D 2022. Some screenshots below 
Thank you ! 
![packages](https://user-images.githubusercontent.com/27021809/161689163-355e660d-6ab7-4c5a-92ba-3cd7258bb520.PNG)
![plugins](https://user-images.githubusercontent.com/27021809/161689174-123fbe35-0626-4d1b-8ef4-84bf9160fa3a.PNG)
![dynamo](https://user-images.githubusercontent.com/27021809/161689181-6b8dfee7-2773-42fa-9bdd-262e831bc81c.PNG)

**Comment by paoloemilioserra** [comment]
you need to download the proper version of CivilConnection, in your case it is the 2022.

**Comment by Mairh93** [comment]
Thank you, is there available ? I can only find the CivilConnection21. 
I use Revit 2021, it would be a problem after with Revit if I download the CivilConnection22?
