### ISSUE TITLE
Version 2023

### ISSUE THREAD

**Issue by ghost** [Autodesk/civilconnection#59]
when will the compilation for 2023 come out

**Comment by iandmcgregor** [comment]
just to be clear, this is an OpenSource community project. If you want any feature built in then you can do that for yourself and contribute it back to the community.
"You are welcome to contribute and help make the toolset better and more complete! The project follows the fork & pull model for accepting contributions. As a contributor, here are the guidelines we would like you to follow..."
See [CONTRIBUTING.md](https://github.com/Autodesk/civilconnection/blob/master/CONTRIBUTING.md) for full details.

**Comment by ghost** [comment]
I appreciate the opportunity, but first I need to familiarize myself with the features.
If it is possible to provide this version I would be very grateful and I will certainly provide feedback and suggestions.

**Comment by paoloemilioserra** [comment]
releases here https://github.com/Autodesk/civilconnection/releases/tag/2023

**Comment by ghost** [comment]
Thank you for your feedback, but I detected the possibility of an error in the "CivilSurface.JoinSurfaces" node, it does not join the input surfaces..
As an example follow this tutorial with several different surfaces and there was no success...
[CivilConnection: Revit, Dynamo, Civil 3D (Povrch TIN na topografii / Surface TIN to Topography)](https://www.youtube.com/watch?v=JXkovB1kkf4)

**Comment by ghost** [comment]
@paoloemilioserra , on my previous request, which was paused after some time, do you have any news? any solution for this reported problem, or update forecast since version 2023 has been updated IronPython.
I would like feedback, unfortunately I am still not expert enough to make changes to the code, but that it would not be discontinued, as it has great use for BIM modellers.
Thanks for making the changes.
Grateful
