### ISSUE TITLE
CivilConnection2023 error when installing 

### ISSUE THREAD

**Issue by MrRed11** [Autodesk/civilconnection#64]
CivilConnection2023 will not load due to an error as shown in the Dynamo package manager. I have Civil3D 2023 installed as well as the CivilConnection2023 plugin that is provided on GitHub.
![C3D error](https://github.com/Autodesk/civilconnection/assets/14155329/b92202c9-3084-48b4-a951-5b55c7279e11)

**Comment by paoloemilioserra** [comment]
CivilConnection is for Revit not for Civil 3D.
