### ISSUE TITLE
Shapes - Points with Z = NaN

### ISSUE THREAD

**Issue by EduardLouis** [Autodesk/civilconnection#7]
Hello,

For some corridors at shapes extraction in the XML file the points are with **Z = "NaN"**
```
<Point X="151694.415803228" Y="214708.731402295" Z="NaN" />
<Point X="151694.433035345" Y="214704.931441367" Z="NaN" />
<Point X="151694.433035345" Y="214704.931441367" Z="NaN" />
<Point X="151694.415803228" Y="214708.731402295" Z="NaN" />
```
From this the shapes are not read. In BaselineRegion I change line 387 and replace with:
`if(x.ToString() != "NaN" && y.ToString() != "NaN" && z.ToString() != "NaN")
{
points.Add(Point.ByCoordinates(x, y, z));
}`

For the moment works fine for me with this change but I'm not sure if should be something more. Convert.ToDouble should return 0 if value is null but it return NaN - maybe the IFormatProvider is wrong)

**Comment by paoloemilioserra** [comment]
@EduardLouis could you please share the Civil 3D dataset in question? How was it created? thanks

**Comment by EduardLouis** [comment]
@paoloemilioserra I sent a graph and a Civil3D file with one corridor at your gmail address from your LinkedIn profile. 
I think error is when baseline starts before profile start.
[image](https://user-images.githubusercontent.com/10221704/63240976-a6098e00-c25a-11e9-9651-b6227102706e.png)

**Comment by EduardLouis** [comment]
@paoloemilioserra 
The same problem with NaN is when extract the elevation at point if the baseline starts before the profile, and baseline / alignment start is negative. 
If I take CoordinateSystemByStation or a point, the result is a CS with Z value = NaN and from here Dynamo stops. 

![image](https://user-images.githubusercontent.com/10221704/63333928-f5c38480-c342-11e9-92c2-1272295a7101.png)

**Comment by danielgijsbers** [comment]
Perhaps it's located in the west of Holland? We don't have Z coordinates. 😁

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by EduardLouis** [comment]
> Perhaps it's located in the west of Holland? We don't have Z coordinates. 😁 

Almost true! 😁

**Comment by EduardLouis** [comment]
@paoloemilioserra 
For some reason **StationOffsetElevationToXYZ**  return NaN if the Profile.ElevationAtStation return NaN. If the vertical profile start at station 0, sometime ElevationAtSation(0) return NaN. 
This happen only for corridors where alignment / baseline starts before vertical profile start. Usually should not be this case but if you don't have full ownership on road design models, you will have this situation.
My solution is to check the coordinates before to create the points, and also if stations is very close to the start or end station, to force the station on profile start / end station. Even this, sometimes return NaN, so I go further and change a little bit the station (with 0.00001m before or after station) and now works in all cases...

**Comment by paoloemilioserra** [comment]
@EduardLouis I'm back now I'll investigate asap.

**Comment by paoloemilioserra** [comment]
@EduardLouis, first thanks for your initial investigation. As stated in the known issues, if the vertical profile does not cover the entire length of the alignment this can generate null Featurelines.
I understand the impact of this when you are not in control of all the elements of the design, but I will not change the logic.
When it comes to shapes or links (as per your initial post), it is not always possible to have enough information to retrieve a Z coordinate as not all the shape points have a code associated and their Z value is most likely different from the value in the baseline you are getting changing the station of very tiny values of the station. What I can do is to try to catch the error and then skip the points that are not "complete", giving evidence in the log file.
Thanks

**Comment by EduardLouis** [comment]
@paoloemilioserra 
Thanks for the support. I applied  the same process to skip the incomplete points. Work fine for me until this moment. I'll test these days you changes.
