### ISSUE TITLE
Mass.ByShapesCreaseStations - Family save location

### ISSUE THREAD

**Issue by Lazarica-t** [Autodesk/civilconnection#9]
Hi Paolo!

Is it possible to change the save location for the families that are generated with Mass.ByShapes**Crease**Stations? (btw it's Crease? not Create in the node name)

I have some projects saved on BIM360 Docs and when I run the scrip it does not save/create the families, but if I detach the project locally it's all good. So I'm thinking it's because it can't access the BIM360 folder maybe.

Best regards!

**Comment by paoloemilioserra** [comment]
Hi @Lazarica-t the name of the node and its behavior are correct and by design.
The reason for not saving the families on BIM360 is that historically they could not be displayed and because the families outside of a Revit project can be outdated, I'm not going to implement these changes.

**Comment by Lazarica-t** [comment]
Thank you for the explanation!
I was hopping to be able to work directly on the Projects saved on BIM360, guess I'll have to use the workaround an detach the project.

Thanks for the response! 
KR,

**Comment by mtanyer** [comment]
Dear Lazarica-t,
Is there a way to save the created families that are generated with Mass.ByShapesCreaseStations to a "specific location" in the harddrive?
Thanks,

**Comment by Lazarica-t** [comment]
@mtanyer out of he box the node doesn't support this feature.. but, maybe you could try some nodes that move/copy the revit families where you need them, after they are generated. I have not personally tried this, but it should work :D

**Comment by mtanyer** [comment]
Thanks Lazarica-t,
Would you please also direct me to a solution for this problem that I am facing up. Tried many things and spend weeks:
https://github.com/Autodesk/civilconnection/issues/66
